import { describe, test, expect, beforeAll } from "bun:test";
import { readFileSync } from "fs";
import { join } from "path";
import init, { FrostDkgSecp256k1, FrostDkgEd25519 } from "@mpc-wallet/core-wasm";

/**
 * Test WASM keystore import functionality with real FROST fixtures.
 *
 * The fixtures under test-data/real-{secp256k1,ed25519}-keystore-p*.json
 * were generated by scripts/gen-frost-fixtures.ts — they're genuine
 * exports from a 2-of-3 DKG ceremony run through the WASM itself.
 * Previous iterations of these tests used hand-crafted objects with
 * dummy string literals like "test_signing_share_..." for the hex
 * fields; those never passed real FROST deserialization and the
 * tests had been .skip'd since inception.
 *
 * These assertions match what export_keystore() actually produces
 * today (min_signers/max_signers/participant_index/curve), not the
 * CLI envelope fields (session_id/device_id) that the WASM doesn't
 * own — those belong to the CLI .dat format layer above.
 */
describe("WASM CLI Keystore Import", () => {
    beforeAll(async () => {
        await init();
    });

    test("should import real secp256k1 keystore and roundtrip through export", async () => {
        const frostDkg = new FrostDkgSecp256k1();
        const keystoreJson = readFileSync(
            join(process.cwd(), "test-data", "real-secp256k1-keystore-p2.json"),
            "utf-8",
        );

        frostDkg.import_keystore(keystoreJson);

        const exported = frostDkg.export_keystore();
        const exportedData = JSON.parse(exported);

        expect(exportedData.min_signers).toBe(2);
        expect(exportedData.max_signers).toBe(3);
        expect(exportedData.participant_index).toBe(2);
        expect(exportedData.curve).toBe("secp256k1");
        expect(exportedData.participant_indices).toEqual([1, 2, 3]);

        // key_package + public_key_package must survive unchanged —
        // they contain the actual FROST secret share material.
        const original = JSON.parse(keystoreJson);
        expect(exportedData.key_package).toBe(original.key_package);
        expect(exportedData.public_key_package).toBe(original.public_key_package);
    });

    test("should import real ed25519 keystore and roundtrip through export", async () => {
        const frostDkg = new FrostDkgEd25519();
        const keystoreJson = readFileSync(
            join(process.cwd(), "test-data", "real-ed25519-keystore-p1.json"),
            "utf-8",
        );

        frostDkg.import_keystore(keystoreJson);

        const exported = frostDkg.export_keystore();
        const exportedData = JSON.parse(exported);

        expect(exportedData.min_signers).toBe(2);
        expect(exportedData.max_signers).toBe(3);
        expect(exportedData.participant_index).toBe(1);
        expect(exportedData.curve).toBe("ed25519");
        expect(exportedData.participant_indices).toEqual([1, 2, 3]);

        const original = JSON.parse(keystoreJson);
        expect(exportedData.key_package).toBe(original.key_package);
        expect(exportedData.public_key_package).toBe(original.public_key_package);
    });

    test("should handle malformed keystore data gracefully", async () => {
        const frostDkg = new FrostDkgSecp256k1();
        
        const malformedKeystore = {
            // Missing required fields
            session_id: "test",
            // threshold missing
            // participants missing
            // key_package missing
        };

        try {
            const keystoreJson = JSON.stringify(malformedKeystore);
            
            // This should either succeed with defaults or throw a clear error
            expect(() => {
                frostDkg.import_keystore(keystoreJson);
            }).toThrow();
            
            console.log("✅ Properly rejected malformed keystore");
            
        } catch (error) {
            // Expected behavior - malformed data should be rejected
            expect(error).toBeDefined();
        }
    });

    test("should validate participant index compatibility", async () => {
        // The CLI uses 0-based indexing internally but the extension uses 1-based
        // Our WASM should handle this conversion properly
        
        const participantIndexTest = {
            cliInternalIndex: 0,     // What CLI stores internally
            extensionIndex: 1,       // What extension expects (1-based)
            expectedWasmBehavior: "convert_0_based_to_1_based"
        };
        
        // Verify our understanding of the index conversion
        expect(participantIndexTest.extensionIndex).toBe(participantIndexTest.cliInternalIndex + 1);
        
        console.log("✅ Participant index conversion validated");
    });
});